### ISSUE TITLE
Add Firefox WebExtensions resources

### ISSUE THREAD

**Issue by vitalets** [vitalets/awesome-browser-extensions-and-apps#2]
hi @Standard8, @kumar303 !

I noticed from [this issue](https://github.com/acvetkov/sinon-chrome/issues/40) of my colleague repo that you are developing a [sample addon repo](https://github.com/mozilla/example-addon-repo) for WebExtensions API in Firefox.

I would like to share with you this awesome list and hope you could suggest some useful resources/links to be added.
One resource I'd like to add is sample addon repo but first I've decided to get your approve that work is more or less done.

Thanks in advance!

/cc @acvetkov

**Comment by Standard8** [comment]
@vitalets I'm just about to investigate switching it back to a hybrid extension. It is also focussed at Firefox development with the test infra it has set up.

However, in talking to people, it seems to be useful to have the WebExtension version, so I'm going to setup another repo that will do that and also be more focussed on non-Mozilla test infra tools, e.g. travis ci. I'll let you know once I've created it.

**Comment by vitalets** [comment]
@Standard8 ok, thank you!

**Comment by kumar303** [comment]
Thanks for sharing! I wasn't aware of some of these tools

**Comment by vitalets** [comment]
@kumar303 You are welcome!
I tried to [submit it to main awesome list](https://github.com/sindresorhus/awesome/pull/781#issuecomment-251881970) to let more people know about it and maybe share something that I'm not aware of but currently list looks not mature enough.
So if you know some useful resources that you are using for extensions, it would be great to add.

**Comment by Standard8** [comment]
Hi @vitalets, it has taken a while, but I've now got the new repo up, you can find it at https://github.com/Standard8/example-webextension/

**Comment by vitalets** [comment]
Thanks @Standard8 ! Added.

PS: Mark, could you give some light are there any plans to support [debugger.\* API](https://developer.chrome.com/extensions/debugger) in Firefox?
